### ISSUE TITLE
Why don't you choose to do it in C ?

### ISSUE THREAD

**Issue by stman** [GildedHonour/shchayki_shchayki#1]
So that we can have better performance & security, but also portability, including in embedded systems that may have no operating systems on them, like microcontrollers, or very light RTOS like "FreeRTOS" running on them ?

If you would agree to change a little bit the goal of your project, to meet those I have mentionned above, I would join forces with you for the development.

Kind regards.

**Comment by GildedHonour** [comment]
Because I don't want to do it in C.
